"""empty message

Revision ID: 5f4f6449ed2d
Revises: 83ca64fe2564
Create Date: 2020-08-02 15:32:52.190532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4f6449ed2d'
down_revision = '83ca64fe2564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mealcategory')
    op.add_column('meals', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meals', 'categorys', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.drop_column('meals', 'category_id')
    op.create_table('mealcategory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('meal_id', sa.INTEGER(), nullable=True),
    sa.Column('categorys_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['categorys_id'], ['categorys.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
